# Generated by Django 3.2.8 on 2021-10-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25)),
                ('government_id', models.CharField(max_length=25)),
                ('second_contact_first_name', models.CharField(blank=True, max_length=50)),
                ('second_contact_last_name', models.CharField(blank=True, max_length=50)),
                ('second_contact_phone_number', models.CharField(blank=True, max_length=25)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='authentication/shop/')),
                ('retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.retailerinfo')),
            ],
        ),
    ]
