# Generated by Django 3.2.8 on 2021-10-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='authentication/shop/')),
                ('retailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.retailerinfo')),
            ],
        ),
    ]
