# Generated by Django 3.2.8 on 2021-10-31 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='picture',
            field=models.ImageField(upload_to='user/shop/'),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('price', models.BigIntegerField()),
                ('defination', models.TextField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image_1', models.ImageField(upload_to='user/ShopProduct/')),
                ('image_2', models.ImageField(blank=True, upload_to='user/ShopProduct/')),
                ('image_3', models.ImageField(blank=True, upload_to='user/ShopProduct/')),
                ('image_4', models.ImageField(blank=True, upload_to='user/ShopProduct/')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
