# Generated by Django 3.2.8 on 2021-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20211208_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
