# Generated by Django 3.2.8 on 2021-12-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20211208_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category',
        ),
    ]
