# Generated by Django 3.2.8 on 2021-12-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_rename_name_productcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.productcategory'),
        ),
    ]
