# Generated by Django 3.2.8 on 2021-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerinfo',
            name='second_contact_first_name',
            field=models.CharField(blank=True, default='no name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailerinfo',
            name='second_contact_last_name',
            field=models.CharField(blank=True, default='no name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailerinfo',
            name='second_contact_phone_number',
            field=models.CharField(blank=True, default=None, max_length=25),
            preserve_default=False,
        ),
    ]
